name: CI
on:
  - push
  - pull_request
  - repository_dispatch
jobs:
  build:
    runs-on: ubuntu-20.04
    environment: ${{ (github.repository == 'jacoco/www.eclemma.org' && github.ref == 'refs/heads/master') && 'sites' || null }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
      - name: 'Build'
        run: ./render.sh
      - name: 'Deploy'
        if: ${{ (github.repository == 'jacoco/www.eclemma.org' && github.ref == 'refs/heads/master') }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
        run: |
          WORKING_DIR="`pwd`/work"
          RESULT_DIR=$WORKING_DIR/result
          TEMP=/tmp/jacoco-snapshot
          mkdir $TEMP
          wget -O $TEMP/download.zip "https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.jacoco&a=jacoco&e=zip&v=LATEST"
          unzip $TEMP/download.zip -d $TEMP

          TARGET=$RESULT_DIR/jacoco/trunk
          mkdir $TARGET
          cp $TEMP/index.html $TARGET
          cp -r $TEMP/doc $TARGET/doc
          cp -r $TEMP/test $TARGET/test
          cp -r $TEMP/coverage $TARGET/coverage

          cd work/result

          # https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/
          touch .nojekyll

          git init
          git config user.name ${GIT_COMMITTER_NAME}
          git config user.email ${GIT_COMMITTER_EMAIL}
          git add .
          git commit -q -m "Automatic deployment"

          git push --force "https://${GH_TOKEN}@github.com/jacoco/jacoco.github.io" master > /dev/null 2>&1

          echo "www.jacoco.org" > CNAME && git add CNAME && git commit -q --amend --reuse-message=HEAD
          git push --force "https://${GH_TOKEN}@github.com/jacoco/jacoco.org" master:gh-pages > /dev/null 2>&1

          echo "www.eclemma.org" > CNAME && git add CNAME && git commit -q --amend --reuse-message=HEAD
          git push --force "https://${GH_TOKEN}@github.com/jacoco/eclemma.org" master:gh-pages > /dev/null 2>&1

          echo "www.eclemma.com" > CNAME && git add CNAME && git commit -q --amend --reuse-message=HEAD
          git push --force "https://${GH_TOKEN}@github.com/jacoco/eclemma.com" master:gh-pages > /dev/null 2>&1
